# Generated by Django 5.2.11 on 2026-03-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourschedule',
            name='available_slots',
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='total_slots',
            field=models.IntegerField(default=0),
        ),
    ]
