# Generated by Django 5.2.12 on 2026-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tourschedule_available_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.CharField(help_text='Ví dụ: 3 ngày 1 đêm', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
