# Generated by Django 5.2.12 on 2026-03-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_duration_days_alter_tour_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
