# Generated by Django 5.2.12 on 2026-03-29 17:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tour_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
