# Generated by Django 5.2.12 on 2026-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='location',
        ),
        migrations.AddField(
            model_name='tourstop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stop_images/'),
        ),
    ]
