# Generated by Django 5.2.12 on 2026-04-06 07:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_continent_name_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Kích hoạt'), ('HIDDEN', 'Ẩn')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
