# Generated by Django 5.2.12 on 2026-04-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_tour_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Kích hoạt'), ('HIDDEN', 'Ẩn')], default='ACTIVE', max_length=10),
        ),
    ]
