# Generated by Django 5.2.13 on 2026-04-20 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_category_name_alter_tour_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Kích hoạt'), ('HIDDEN', 'Ẩn')], default='ACTIVE'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='total_slots',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
