# Generated by Django 5.2.13 on 2026-04-20 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_category_name_alter_tour_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='route',
        ),
        migrations.AddField(
            model_name='routestop',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
        migrations.DeleteModel(
            name='TourRoute',
        ),
    ]
