# Generated by Django 5.2.13 on 2026-04-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_remove_routestop_route_routestop_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
    ]
