# Generated by Django 5.2.14 on 2026-05-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_alter_routestop_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='tour',
        ),
        migrations.DeleteModel(
            name='TourStop',
        ),
        migrations.DeleteModel(
            name='RouteStop',
        ),
    ]
