# Generated by Django 5.2.12 on 2026-04-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage_replied_at_contactmessage_reply_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='reply_text',
        ),
    ]
