# Generated by Django 5.2.13 on 2026-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Người dùng'), ('staff', 'Nhân viên'), ('admin', 'Quản trị')], default='user', max_length=16),
        ),
    ]
