# Generated by Django 5.2.14 on 2026-05-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code_expires_at',
        ),
    ]
