# Generated by Django 5.2.11 on 2026-03-02 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_people', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Chưa đặt'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy')], default='PENDING')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('tour_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourschedule')),
            ],
        ),
    ]
